name: flutter_media_picker
description: "Flutter media picker plugin"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.1.1
  photo_manager_image_provider: ^2.1.1
  flutter_sticky_header: ^0.6.5
  camera: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.xlabs.flutter_media_picker
        pluginClass: FlutterMediaPickerPlugin
      ios:
        pluginClass: FlutterMediaPickerPlugin
